# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-php56:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:5.6-alpine" php56/alpine/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:5.6-apache" php56/apache/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:5.6-stretch php56/stretch/
    - docker push "$CI_REGISTRY_IMAGE"

build-php72:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:7.2-alpine" php72/alpine/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:7.2-apache" php72/apache/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:7.2-stretch php72/stretch/
    - docker push "$CI_REGISTRY_IMAGE"

build-php73:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:7.3-alpine" php73/alpine/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:7.3-apache" php73/apache/
    - docker build --pull -t "$CI_REGISTRY_IMAGE:7.3-stretch php73/stretch/
    - docker push "$CI_REGISTRY_IMAGE"
